### ISSUE TITLE
Different background color on input/output code blocks

### ISSUE THREAD

**Issue by yanaga** [redhat-developer-demos/kubernetes-tutorial#15]
I believe it would be much easier to read the tutorial if we could have different background colors for input/output. Having something like this would probably allow us to automatically create the copy button on the section.

I google a lot to try to find how to add a css style to a section in Antora, but had no success. @lordofthejars, any tips? I can do it, but I just need some light on this subject.

**Comment by lordofthejars** [comment]
Yes you need to provide it as a supplemental-ui:
https://github.com/redhat-developer-demos/rhd-tutorial-template/tree/master/supplemental-ui

And register them:
https://github.com/redhat-developer-demos/rhd-tutorial-template/blob/master/supplemental-ui/partials/footer-scripts.hbs

Missatge de Edson Yanaga <notifications@github.com> del dia dg., 3 de maig
2020 a les 22:11:

**Comment by yanaga** [comment]
I already know how to create a supplemental-ui, but I don't know how to apply a css in a piece of asciidoc so that it will include my additional css style.

I already have the css style in my supplemental-ui. How do I apply it to block of text?
