### ISSUE TITLE
Reduce the use of "&&" in the installation section

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/kubernetes-tutorial#17]
Joining these commands reduces learnability.  It is better for the reader to see, use and attempt to understand the commands individually.  Especially commands that need to be repeated if a new terminal window is opened or the laptop rebooted.

As an example:
git clone https://github.com/redhat-developer-demos/kubernetes-tutorial kubernetes-tutorial && \
export TUTORIAL_HOME="$(pwd)/kubernetes-tutorial" && \
cd $TUTORIAL_HOME

**Comment by kameshsampath** [comment]
@lordofthejars  this thing comes in the common part of the tutorial, since you are hacking it I leave it to you.

**Comment by lordofthejars** [comment]
Fixed at commons repo. https://github.com/redhat-developer-demos/rhd-tutorial-common/commit/a6a02696238beaea65b720046a856bda2c3622b4

**Comment by kameshsampath** [comment]
Thanks Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
