### ISSUE TITLE
Slight error in the Dev Nation Kubernetes Tutorial - 2. Beginner - kubectl - Talk To The App

### ISSUE THREAD

**Issue by wkremser** [redhat-developer-demos/kubernetes-tutorial#18]
Hi Sebastien, hi Burr, 

Your livestream today was incredible again :) .. I finally got the time to play with the kubernetes tutorial.

I found a little inconsistence in it.

In the Section “Talk to the App” on 2. Beginner / kubectl there is a slight error in the command querying the IP address.
The command "IP=$(minikube ip)” should be changed to "IP=$(minikube ip -p devnation)"

It took me quite a while to figure that out.

With regards 
Wolfgang “DJ Madie” Kremser

**Comment by lordofthejars** [comment]
Thank you very much for your comment, this is fixed now.
