### ISSUE TITLE
minikube -p devnation docker-env

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/kubernetes-tutorial#21]
This module 
https://redhat-developer-demos.github.io/kubernetes-tutorial/kubernetes-tutorial/building-images.html
assumes the following has not been executed:
eval $(minikube docker-env -p devnation)
which is at the bottom of this page
https://redhat-developer-demos.github.io/kubernetes-tutorial/kubernetes-tutorial/installation.html#verify-setup

**Comment by lordofthejars** [comment]
@burrsutter I am not following you, in the bottom of the page of installation we explain the `eval` thing. Then you say that in the building images page assumes that this `eval` has not been executed, but I do not catch you what you mean as the setup has been executed before this section. You mean that we need to add a remainder?

**Comment by burrsutter** [comment]
The building images chapter ASSUMES the reader has NOT used docker-env.  The building images chapter assumes the reader is working with their Docker for Mac/Windows; however, if the reader has been following the overall flow of the doc they would have issued the 'docker-env' command and then the building images instructions would fail.   For instance, in building images, the reader is told to use 'curl localhost:8080' but that will only work if the end-user is using docker for mac instead of minikube.  With minikube via docker-env, the reader would need to use the minikube ip.

**Comment by lordofthejars** [comment]
Gotcha now. Sorry. Fixing it now.
