### ISSUE TITLE
kubectl apply -f myboot-pod-volume.yml

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/kubernetes-tutorial#22]
In https://redhat-developer-demos.github.io/kubernetes-tutorial/kubernetes-tutorial/volumes-persistentvolumes.html

Does not use the style of 
apps/kubefiles/myboot-pod-volume.yml
as seen in the overall document

**Comment by lordofthejars** [comment]
The reason is that a `persistentvolumes` is not tight to any application, it is something generic where any application can use it. So when it is that the `myboot` application uses the volume then it follows the same style but when it is a generic `pv` then I use a more generic nomenclature.

**Comment by burrsutter** [comment]
But this means the reader can not just copy & paste the command.  Throughout the document, the reader is allowed to copy & paste commands like:
kubectl apply -f apps/kubefiles/myboot-deployment.yml
but in this case the missing "apps/kubefiles" means the command is not copy & pasteable in the style of previous modules.
