### ISSUE TITLE
LoadBalancer on minikube/baremetal (enhancement)

### ISSUE THREAD

**Issue by survivant** [redhat-developer-demos/kubernetes-tutorial#4]
for minikube or baremetal you could specify that it's possible to install MetalLB  (https://metallb.universe.tf/)  as another option than ingress.

**Comment by burrsutter** [comment]
Thank you for your comment and thoughts.  At this time, we do not find that MetalLB has enough popularity for us to work it into the overall Tutorial.  In general, Ngnix, ha-proxy and Envoy are the winners in the Kubernetes ingress world and we try to keep the Tutorial content fairly universal.

**Comment by kameshsampath** [comment]
projectcontour.io made its way to CNCF; a good candidate to show Ingress capabilities

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
